model: 
  isMix: False
  split_count: 10
  # isMix为False时生效
  name: Feature-XGBoost
  # isMix为True时生效
  model_list:
    - Feature-XGBoost
    - Feature-RandomForest
    - Feature-AdaBoost


visualization:
  html: False


